// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeProject.Infrastructure.DbContext;

#nullable disable

namespace PracticeProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241215174357_UpdateEntityModels")]
    partial class UpdateEntityModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("af46567a-2564-491a-8f47-7942bd906590"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Mouse",
                            Price = 821.45m,
                            StockQuantity = 97
                        },
                        new
                        {
                            Id = new Guid("f356eb68-5291-4206-bc62-8e6ab0e33a50"),
                            Category = "Clothing",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Keyboard",
                            Price = 23.15m,
                            StockQuantity = 357
                        },
                        new
                        {
                            Id = new Guid("a399c158-a08b-486e-94b0-6cfaefd677d3"),
                            Category = "Electronics",
                            Description = "Elegant and modern wristwatch",
                            Name = "Projector",
                            Price = 745.92m,
                            StockQuantity = 19
                        },
                        new
                        {
                            Id = new Guid("40e58668-45cb-4e51-a08e-8bf05a9b7b09"),
                            Category = "Other",
                            Description = "Elegant and modern wristwatch",
                            Name = "Wireless Keyboard",
                            Price = 27.94m,
                            StockQuantity = 390
                        },
                        new
                        {
                            Id = new Guid("78a2cd11-d53c-4ea9-b9c3-47668eeb0f68"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "External Hard Drive",
                            Price = 50.74m,
                            StockQuantity = 368
                        },
                        new
                        {
                            Id = new Guid("bea9debc-c889-4d9e-8058-272da76fdbe7"),
                            Category = "Electronics",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Earbuds",
                            Price = 149.43m,
                            StockQuantity = 37
                        },
                        new
                        {
                            Id = new Guid("2e469e5a-43c6-4831-8a69-0a19117caa70"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "Camera",
                            Price = 911.86m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = new Guid("24f89608-f520-4412-b4b8-5af6f29cb3ad"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Bluetooth Speaker",
                            Price = 161.79m,
                            StockQuantity = 450
                        },
                        new
                        {
                            Id = new Guid("02b0615b-7dc6-4d68-b7c6-352c992e6583"),
                            Category = "Other",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Monitor",
                            Price = 566.7m,
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = new Guid("090438a5-e073-4410-9d96-5e455004cad7"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Speaker",
                            Price = 571.85m,
                            StockQuantity = 77
                        },
                        new
                        {
                            Id = new Guid("7bf97a49-811a-4daa-a501-66736f867f3f"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Tablet",
                            Price = 926.54m,
                            StockQuantity = 493
                        },
                        new
                        {
                            Id = new Guid("704ef17d-315b-4fde-a8ec-c0290a837b91"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Speaker",
                            Price = 299.54m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = new Guid("e86f1e18-bcb5-4aa6-9211-82d1bbbc9f0a"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Gaming Console",
                            Price = 152.87m,
                            StockQuantity = 387
                        },
                        new
                        {
                            Id = new Guid("313d63ff-7d43-4276-a44f-d49bbc8839cf"),
                            Category = "Other",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Smartphone",
                            Price = 535.98m,
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = new Guid("b2fb2042-2076-4c5a-9de9-26887ea4455e"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Bluetooth Speaker",
                            Price = 575.85m,
                            StockQuantity = 29
                        },
                        new
                        {
                            Id = new Guid("af6e2699-2a2a-46cd-8096-8ec9f54cf562"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Monitor",
                            Price = 814.77m,
                            StockQuantity = 326
                        },
                        new
                        {
                            Id = new Guid("2c91d366-c4d6-4c09-ae0f-0091303b89a5"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Camera",
                            Price = 614.92m,
                            StockQuantity = 402
                        },
                        new
                        {
                            Id = new Guid("1b411f73-1399-45d7-a29c-ce7883369204"),
                            Category = "Electronics",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Monitor",
                            Price = 641.78m,
                            StockQuantity = 492
                        },
                        new
                        {
                            Id = new Guid("d6d3f33c-6319-4a43-9beb-058b150913de"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Tablet",
                            Price = 885.78m,
                            StockQuantity = 329
                        },
                        new
                        {
                            Id = new Guid("c097a135-c163-4051-ab9d-b5fec7ea2c4d"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "VR Headset",
                            Price = 720.15m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = new Guid("bf78505b-9d47-4384-9072-7cd4294b86e0"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Smartphone",
                            Price = 295.96m,
                            StockQuantity = 99
                        },
                        new
                        {
                            Id = new Guid("a46a054b-9f18-4210-943d-e8ee09ede007"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Printer",
                            Price = 85.1m,
                            StockQuantity = 63
                        },
                        new
                        {
                            Id = new Guid("35560afb-d0cf-401d-b690-f5e5fb7c8e76"),
                            Category = "Other",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "External Hard Drive",
                            Price = 898.1m,
                            StockQuantity = 94
                        },
                        new
                        {
                            Id = new Guid("9b8462c3-0213-45d7-ae5c-9545b36d9480"),
                            Category = "Clothing",
                            Description = "Durable and stylish backpack",
                            Name = "Keyboard",
                            Price = 591.98m,
                            StockQuantity = 443
                        },
                        new
                        {
                            Id = new Guid("73df1950-d695-4b75-9361-b4c736a33385"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Projector",
                            Price = 380.9m,
                            StockQuantity = 144
                        },
                        new
                        {
                            Id = new Guid("e58fd23d-bb91-41a0-9c96-a654057d2724"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Wireless Printer",
                            Price = 758.08m,
                            StockQuantity = 344
                        },
                        new
                        {
                            Id = new Guid("e3c24381-6b26-4d5a-8f87-bc36e95793ef"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Tablet",
                            Price = 298.94m,
                            StockQuantity = 211
                        },
                        new
                        {
                            Id = new Guid("65d4d07f-4cd8-43be-8bfc-bcc82c94f4b4"),
                            Category = "Electronics",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Monitor",
                            Price = 309.9m,
                            StockQuantity = 270
                        },
                        new
                        {
                            Id = new Guid("3e003da8-e88f-4aef-8a4b-b69a0d0c16b7"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "USB Flash Drive",
                            Price = 425.68m,
                            StockQuantity = 361
                        },
                        new
                        {
                            Id = new Guid("26a2f976-9633-4722-9cf9-93228ee8f1e3"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Fitness Tracker",
                            Price = 37.19m,
                            StockQuantity = 288
                        },
                        new
                        {
                            Id = new Guid("7807f809-7875-4760-8b36-510e217f96bc"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Earbuds",
                            Price = 802.06m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = new Guid("8020dd83-14f9-4371-8161-abba3335d1b9"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Fitness Tracker",
                            Price = 223.03m,
                            StockQuantity = 184
                        },
                        new
                        {
                            Id = new Guid("f993a218-6692-4a1b-996a-3aae76b90ffb"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Wireless Keyboard",
                            Price = 820.99m,
                            StockQuantity = 13
                        },
                        new
                        {
                            Id = new Guid("02100e13-50e4-4b3d-9bf6-04af9cf8f475"),
                            Category = "Books",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Monitor",
                            Price = 518.41m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = new Guid("a97cf430-bda6-4b35-b6a0-c1bde8b81f11"),
                            Category = "Clothing",
                            Description = "Durable and stylish backpack",
                            Name = "Smartphone",
                            Price = 646.0m,
                            StockQuantity = 179
                        },
                        new
                        {
                            Id = new Guid("9c88025b-f441-475d-8183-2e2a28cc9ac3"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Webcam",
                            Price = 910.17m,
                            StockQuantity = 377
                        },
                        new
                        {
                            Id = new Guid("0881dbf4-ca55-46c1-81ee-7c8aabc31012"),
                            Category = "Books",
                            Description = "Elegant and modern wristwatch",
                            Name = "Printer",
                            Price = 651.38m,
                            StockQuantity = 387
                        },
                        new
                        {
                            Id = new Guid("72def9b7-7d43-4b99-acc4-503881b6e3d2"),
                            Category = "Electronics",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Camera",
                            Price = 135.56m,
                            StockQuantity = 104
                        },
                        new
                        {
                            Id = new Guid("9e066adc-ff7d-4ba2-9a22-a9eedc327216"),
                            Category = "Home",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Smartwatch",
                            Price = 410.28m,
                            StockQuantity = 131
                        },
                        new
                        {
                            Id = new Guid("682fc03f-7a65-4054-8642-621217c859dc"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Wireless Router",
                            Price = 400.59m,
                            StockQuantity = 63
                        },
                        new
                        {
                            Id = new Guid("d1c0b4bf-e8d1-45bf-8c46-f60f0d8fcad3"),
                            Category = "Home",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Gaming Mouse",
                            Price = 822.44m,
                            StockQuantity = 493
                        },
                        new
                        {
                            Id = new Guid("8a85e9c9-cabb-44cd-8b29-956a2d3efbc7"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Wireless Printer",
                            Price = 844.09m,
                            StockQuantity = 53
                        },
                        new
                        {
                            Id = new Guid("9168c928-d33b-45d6-83cb-cbc568e91073"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Wireless Router",
                            Price = 567.8m,
                            StockQuantity = 322
                        },
                        new
                        {
                            Id = new Guid("31f56c88-edf6-4e50-bbbb-0c7b46748a79"),
                            Category = "Other",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Mouse",
                            Price = 814.91m,
                            StockQuantity = 127
                        },
                        new
                        {
                            Id = new Guid("62d06097-3f2d-485c-a5cd-f371c557a5b4"),
                            Category = "Electronics",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Smartwatch",
                            Price = 208.85m,
                            StockQuantity = 409
                        },
                        new
                        {
                            Id = new Guid("311c0d7d-6ab5-4dd9-b866-a3897ae21eda"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Headphones",
                            Price = 392.45m,
                            StockQuantity = 370
                        },
                        new
                        {
                            Id = new Guid("f745432a-cf39-436f-ac92-d7c50535931b"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Camera",
                            Price = 652.54m,
                            StockQuantity = 474
                        },
                        new
                        {
                            Id = new Guid("974152c5-e121-4c5e-a876-cc3f2e0cf02f"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Headphones",
                            Price = 524.18m,
                            StockQuantity = 472
                        },
                        new
                        {
                            Id = new Guid("7015c28f-e89a-4cc6-a067-529a54909659"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Fitness Tracker",
                            Price = 714.87m,
                            StockQuantity = 246
                        },
                        new
                        {
                            Id = new Guid("45218055-86df-40c4-bd8d-6a683dc15c73"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "Headphones",
                            Price = 639.54m,
                            StockQuantity = 66
                        },
                        new
                        {
                            Id = new Guid("000e6c99-5b1c-4502-b9f8-a90a1f84e4e8"),
                            Category = "Home",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Speaker",
                            Price = 118.36m,
                            StockQuantity = 81
                        },
                        new
                        {
                            Id = new Guid("646aff46-25fc-4eb4-97a9-36cf9025e291"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Portable Charger",
                            Price = 108.87m,
                            StockQuantity = 499
                        },
                        new
                        {
                            Id = new Guid("21cd4ed9-aec6-4d5c-9522-6f4bdc55f657"),
                            Category = "Books",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Smartwatch",
                            Price = 43.38m,
                            StockQuantity = 167
                        },
                        new
                        {
                            Id = new Guid("58ef3523-00c0-40c6-89d2-21079f935b2c"),
                            Category = "Clothing",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Camera",
                            Price = 890.69m,
                            StockQuantity = 201
                        },
                        new
                        {
                            Id = new Guid("604c4ff2-588e-424a-8aaf-55ecf8e7d0bc"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Smartphone",
                            Price = 310.15m,
                            StockQuantity = 223
                        },
                        new
                        {
                            Id = new Guid("56717e3a-0fdf-464f-beb0-a0883aa95311"),
                            Category = "Other",
                            Description = "Elegant and modern wristwatch",
                            Name = "Gaming Console",
                            Price = 440.81m,
                            StockQuantity = 148
                        },
                        new
                        {
                            Id = new Guid("b3f5f795-1364-4b81-a68b-966e362379c0"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Tablet",
                            Price = 647.31m,
                            StockQuantity = 491
                        },
                        new
                        {
                            Id = new Guid("771538a8-b71a-4789-a3d0-07e661380937"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "USB Flash Drive",
                            Price = 918.36m,
                            StockQuantity = 482
                        },
                        new
                        {
                            Id = new Guid("3bd492c8-b42e-4927-9ca6-01ba7d782b7a"),
                            Category = "Electronics",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Camera",
                            Price = 491.33m,
                            StockQuantity = 64
                        },
                        new
                        {
                            Id = new Guid("7d2566f5-d6b5-4be1-a63c-8c350d784091"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "Projector",
                            Price = 810.26m,
                            StockQuantity = 336
                        },
                        new
                        {
                            Id = new Guid("b721676a-2ce1-4de9-a419-bdd6e17db133"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Camera",
                            Price = 990.73m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = new Guid("d00bd6b2-0ac9-4e80-a4d7-9dc34a45e357"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Action Camera",
                            Price = 272.44m,
                            StockQuantity = 479
                        },
                        new
                        {
                            Id = new Guid("03b4d595-3333-4784-82ae-4e83c8eaddab"),
                            Category = "Other",
                            Description = "Elegant and modern wristwatch",
                            Name = "Camera",
                            Price = 865.76m,
                            StockQuantity = 327
                        },
                        new
                        {
                            Id = new Guid("d7bd83ad-797e-48a3-a83a-f0755a51639c"),
                            Category = "Clothing",
                            Description = "Durable and stylish backpack",
                            Name = "Headphones",
                            Price = 960.7m,
                            StockQuantity = 397
                        },
                        new
                        {
                            Id = new Guid("07ca935b-4e5a-431f-a98c-68eed6d04fff"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Graphics Card",
                            Price = 582.21m,
                            StockQuantity = 477
                        },
                        new
                        {
                            Id = new Guid("252d8e88-8f00-4734-95a5-6665c2139683"),
                            Category = "Electronics",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Laptop",
                            Price = 848.84m,
                            StockQuantity = 72
                        },
                        new
                        {
                            Id = new Guid("7a52fa81-8036-4633-a559-829fa135d8f7"),
                            Category = "Home",
                            Description = "Elegant and modern wristwatch",
                            Name = "Laptop",
                            Price = 229.68m,
                            StockQuantity = 414
                        },
                        new
                        {
                            Id = new Guid("dcf9f670-958d-47ad-8b70-0681da4698a2"),
                            Category = "Home",
                            Description = "Elegant and modern wristwatch",
                            Name = "Smartwatch",
                            Price = 248.1m,
                            StockQuantity = 312
                        },
                        new
                        {
                            Id = new Guid("f164a34a-2865-40f4-b6df-0a516a03aa6f"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "Graphics Card",
                            Price = 8.59m,
                            StockQuantity = 33
                        },
                        new
                        {
                            Id = new Guid("62a98303-cc3c-4d35-9078-a13166b324d2"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Portable Charger",
                            Price = 180.06m,
                            StockQuantity = 317
                        },
                        new
                        {
                            Id = new Guid("e0b8cef9-3faf-4cc4-9494-f09bc6db4d88"),
                            Category = "Books",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Smartphone",
                            Price = 116.07m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("c6eba505-b588-4d77-81f3-4dc324dbc786"),
                            Category = "Other",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Projector",
                            Price = 436.25m,
                            StockQuantity = 144
                        },
                        new
                        {
                            Id = new Guid("20edfc96-5227-45b6-90fd-78c522e50b02"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Camera",
                            Price = 398.29m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("a783b24f-e11c-4f28-9706-e9501a2320fc"),
                            Category = "Electronics",
                            Description = "Durable and stylish backpack",
                            Name = "Laptop",
                            Price = 352.1m,
                            StockQuantity = 327
                        },
                        new
                        {
                            Id = new Guid("c3c2ef85-7e76-4ea1-bed7-bad724145fc0"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "External Hard Drive",
                            Price = 499.56m,
                            StockQuantity = 479
                        },
                        new
                        {
                            Id = new Guid("0c6a2cf9-3b4d-42cc-8c41-02cbeff12b4b"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Router",
                            Price = 441.69m,
                            StockQuantity = 484
                        },
                        new
                        {
                            Id = new Guid("50d98327-5455-4bf0-bc64-9d0995f9678a"),
                            Category = "Electronics",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Gaming Console",
                            Price = 644.42m,
                            StockQuantity = 122
                        },
                        new
                        {
                            Id = new Guid("49cc6197-f582-4040-bc57-31d4110675bb"),
                            Category = "Books",
                            Description = "Elegant and modern wristwatch",
                            Name = "Headphones",
                            Price = 761.89m,
                            StockQuantity = 232
                        },
                        new
                        {
                            Id = new Guid("d3c8c1c4-da36-4edb-8551-3ed2aad189c2"),
                            Category = "Other",
                            Description = "Elegant and modern wristwatch",
                            Name = "VR Headset",
                            Price = 12.34m,
                            StockQuantity = 339
                        },
                        new
                        {
                            Id = new Guid("6a0feb92-8d23-4e9e-b8ff-ad6119d4a949"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Monitor",
                            Price = 311.53m,
                            StockQuantity = 435
                        },
                        new
                        {
                            Id = new Guid("4709ff36-00a8-4f9c-be82-06bf233e5b0a"),
                            Category = "Other",
                            Description = "Elegant and modern wristwatch",
                            Name = "Webcam",
                            Price = 237.49m,
                            StockQuantity = 93
                        },
                        new
                        {
                            Id = new Guid("7b21e62a-7191-4da4-be2d-0f10e9c5f835"),
                            Category = "Books",
                            Description = "Durable and stylish backpack",
                            Name = "Speaker",
                            Price = 997.51m,
                            StockQuantity = 72
                        },
                        new
                        {
                            Id = new Guid("756db979-f5ea-4b81-a913-796274ea3b6b"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Printer",
                            Price = 504.47m,
                            StockQuantity = 313
                        },
                        new
                        {
                            Id = new Guid("33760a14-aec4-4aba-95f1-651a1a2710dc"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Fitness Tracker",
                            Price = 611.86m,
                            StockQuantity = 189
                        },
                        new
                        {
                            Id = new Guid("c84c9d89-9560-4ebf-9f66-6f8221e2b361"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Wireless Earbuds",
                            Price = 613.67m,
                            StockQuantity = 471
                        },
                        new
                        {
                            Id = new Guid("df414527-8f63-4c15-b75b-e6c58874a5f5"),
                            Category = "Other",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Laptop",
                            Price = 904.82m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = new Guid("acc21795-a5e6-43b8-a9ad-49272fbc85b5"),
                            Category = "Home",
                            Description = "Soft and comfortable t-shirt",
                            Name = "USB Flash Drive",
                            Price = 754.93m,
                            StockQuantity = 193
                        },
                        new
                        {
                            Id = new Guid("b5b95b29-a291-45ec-8c3d-e16bf6d6933b"),
                            Category = "Clothing",
                            Description = "Durable and stylish backpack",
                            Name = "Smartwatch",
                            Price = 681.24m,
                            StockQuantity = 44
                        },
                        new
                        {
                            Id = new Guid("94e92a9f-d010-4c27-acc0-53c6b242c618"),
                            Category = "Books",
                            Description = "Elegant and modern wristwatch",
                            Name = "Keyboard",
                            Price = 894.05m,
                            StockQuantity = 487
                        },
                        new
                        {
                            Id = new Guid("14eb3cf4-ed14-46eb-ac5f-6ce066864d2c"),
                            Category = "Other",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Tablet",
                            Price = 758.6m,
                            StockQuantity = 490
                        },
                        new
                        {
                            Id = new Guid("d3780a3a-b8bd-4d51-a84c-db4b047dbb45"),
                            Category = "Home",
                            Description = "Elegant and modern wristwatch",
                            Name = "Wireless Earbuds",
                            Price = 190.34m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("5dd2bed0-c46d-4f1f-8c57-3cb671846a14"),
                            Category = "Other",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "Monitor",
                            Price = 588.13m,
                            StockQuantity = 474
                        },
                        new
                        {
                            Id = new Guid("f76c82dc-f850-4478-b4a7-539c08782621"),
                            Category = "Home",
                            Description = "Versatile and practical kitchen appliance",
                            Name = "VR Headset",
                            Price = 504.98m,
                            StockQuantity = 441
                        },
                        new
                        {
                            Id = new Guid("055e7a58-5167-4507-9d62-c11ad1903117"),
                            Category = "Electronics",
                            Description = "Elegant and modern wristwatch",
                            Name = "Wireless Router",
                            Price = 231.91m,
                            StockQuantity = 205
                        },
                        new
                        {
                            Id = new Guid("457eccda-6867-4461-9d2c-e6b9b7bc3fdf"),
                            Category = "Home",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Graphics Card",
                            Price = 873.11m,
                            StockQuantity = 107
                        },
                        new
                        {
                            Id = new Guid("526a6571-d79d-467d-92f8-b7f793ea001c"),
                            Category = "Home",
                            Description = "Durable and stylish backpack",
                            Name = "Microphone",
                            Price = 289.89m,
                            StockQuantity = 170
                        },
                        new
                        {
                            Id = new Guid("d884cf5a-57e8-4fad-a84f-e2834a109a3b"),
                            Category = "Other",
                            Description = "Durable and stylish backpack",
                            Name = "Wireless Keyboard",
                            Price = 517.79m,
                            StockQuantity = 68
                        },
                        new
                        {
                            Id = new Guid("ac2ad2d7-fc44-43fb-9e75-82bfcb5da3fa"),
                            Category = "Clothing",
                            Description = "Elegant and modern wristwatch",
                            Name = "Wireless Keyboard",
                            Price = 243.58m,
                            StockQuantity = 121
                        },
                        new
                        {
                            Id = new Guid("0a9ffd93-2a08-45f5-a2ff-8bb1df8d97bc"),
                            Category = "Clothing",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Wireless Mouse",
                            Price = 708.8m,
                            StockQuantity = 209
                        },
                        new
                        {
                            Id = new Guid("2253b37d-751b-44a1-946c-a7cb77d3df9f"),
                            Category = "Books",
                            Description = "Soft and comfortable t-shirt",
                            Name = "Fitness Tracker",
                            Price = 198.98m,
                            StockQuantity = 84
                        });
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.IdentityEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.IdentityEntities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dbe5ec6-0c03-437b-ba60-d507711ef09e"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("4d5dc6f5-7358-4b9f-8118-5966bebdc294"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.Order", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.IdentityEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("PracticeProject.Core.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("PracticeProject.Core.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PracticeProject.Core.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
